import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Hero from "../components/hero";
import Layout from "../components/layout";

export default function Home() {
	return (
		<Layout>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Hero />
		</Layout>
	);
}
